# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NodeID', models.CharField(max_length=10)),
                ('Time', models.CharField(max_length=10)),
                ('Accelerometer', models.CharField(max_length=10)),
                ('Pressure', models.CharField(max_length=10)),
                ('Light', models.CharField(max_length=10)),
                ('Sound', models.CharField(max_length=10)),
                ('Motion', models.CharField(max_length=10)),
                ('Humidity', models.CharField(max_length=10)),
                ('Thermometer', models.CharField(max_length=10)),
            ],
        ),
    ]
